// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	domain "speed-typing-text-service/internal/core/domain"

	mock "github.com/stretchr/testify/mock"
)

// CodeExampleRepository is an autogenerated mock type for the CodeExampleRepository type
type CodeExampleRepository struct {
	mock.Mock
}

// GetCodeExamples provides a mock function with given fields:
func (_m *CodeExampleRepository) GetCodeExamples() []domain.CodeExample {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCodeExamples")
	}

	var r0 []domain.CodeExample
	if rf, ok := ret.Get(0).(func() []domain.CodeExample); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CodeExample)
		}
	}

	return r0
}

// GetCodeExamplesByProgrammingLanguageUUID provides a mock function with given fields: programmingLanguageUUID
func (_m *CodeExampleRepository) GetCodeExamplesByProgrammingLanguageUUID(programmingLanguageUUID string) ([]domain.CodeExample, error) {
	ret := _m.Called(programmingLanguageUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetCodeExamplesByProgrammingLanguageUUID")
	}

	var r0 []domain.CodeExample
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domain.CodeExample, error)); ok {
		return rf(programmingLanguageUUID)
	}
	if rf, ok := ret.Get(0).(func(string) []domain.CodeExample); ok {
		r0 = rf(programmingLanguageUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CodeExample)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(programmingLanguageUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProgrammingLanguages provides a mock function with given fields:
func (_m *CodeExampleRepository) GetProgrammingLanguages() []domain.ProgrammingLanguage {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProgrammingLanguages")
	}

	var r0 []domain.ProgrammingLanguage
	if rf, ok := ret.Get(0).(func() []domain.ProgrammingLanguage); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ProgrammingLanguage)
		}
	}

	return r0
}

// NewCodeExampleRepository creates a new instance of CodeExampleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeExampleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeExampleRepository {
	mock := &CodeExampleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
